<?xml version="1.0" encoding="UTF-8"?>
<robot generated="20180910 12:22:28.550" generator="Robot 3.0.4 (Python 2.7.12 on linux2)">
<suite source="/home/gigavoice/testsRob/test2.robot" id="s1" name="Test2">
<test id="s1-t1" name="Lunch Browser">
<kw name="Set Environment Variable" library="OperatingSystem">
<doc>Sets an environment variable to a specified value.</doc>
<arguments>
<arg>chromedriver</arg>
<arg>/usr/bin/</arg>
</arguments>
<msg timestamp="20180910 12:22:28.744" level="INFO">Environment variable 'chromedriver' set to value '/usr/bin/'.</msg>
<status status="PASS" endtime="20180910 12:22:28.744" starttime="20180910 12:22:28.743"></status>
</kw>
<kw name="Open Browser" library="Selenium2Library">
<doc>Opens a new browser instance to the given ``url``.</doc>
<arguments>
<arg>https://www.google.com</arg>
<arg>chrome</arg>
<arg>None</arg>
<arg>http://localhost:4445/wd/hub</arg>
</arguments>
<msg timestamp="20180910 12:22:28.745" level="INFO">Opening browser 'chrome' to base url 'https://www.google.com' through remote server at 'http://localhost:4445/wd/hub'.</msg>
<msg timestamp="20180910 12:22:28.746" level="INFO">Could not connect to port 4445 on host localhost</msg>
<msg timestamp="20180910 12:22:28.746" level="INFO">Could not get IP address for host: localhost</msg>
<msg timestamp="20180910 12:22:28.752" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862d10&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20180910 12:22:28.753" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862e50&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20180910 12:22:28.754" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862fd0&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
<kw name="Capture Page Screenshot" library="Selenium2Library">
<doc>Takes screenshot of the current page and embeds it into log file.</doc>
<msg timestamp="20180910 12:22:28.755" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" endtime="20180910 12:22:28.756" starttime="20180910 12:22:28.755"></status>
</kw>
<msg timestamp="20180910 12:22:28.758" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4445): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862790&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</msg>
<status status="FAIL" endtime="20180910 12:22:28.758" starttime="20180910 12:22:28.744"></status>
</kw>
<status status="FAIL" endtime="20180910 12:22:28.758" critical="yes" starttime="20180910 12:22:28.742">MaxRetryError: HTTPConnectionPool(host='localhost', port=4445): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862790&gt;: Failed to establish a new connection: [Errno 111] Connection refused',))</status>
</test>
<doc>Tests to verify that the browser lunches</doc>
<status status="FAIL" endtime="20180910 12:22:28.760" starttime="20180910 12:22:28.552"></status>
</suite>
<statistics>
<total>
<stat fail="1" pass="0">Critical Tests</stat>
<stat fail="1" pass="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat fail="1" id="s1" name="Test2" pass="0">Test2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20180910 12:22:28.752" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862d10&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20180910 12:22:28.753" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862e50&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
<msg timestamp="20180910 12:22:28.754" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x7fbeca862fd0&gt;: Failed to establish a new connection: [Errno 111] Connection refused',)': /wd/hub/session</msg>
</errors>
</robot>
